### PR TITLE
feat(docs): document the Trunk integration for sqlfmt

### LINKED ISSUE #10: Add Trunk integration
A community member contributed this integration:

https://github.com/trunk-io/plugins/pull/37

Need to add an integration page and maybe mention it in the tools list on the homepage.

### PR DESCRIPTION
**Pull request by sxlijin**
Fixes #10 

I would much prefer to check in the images as LFS files, but because it's not yet enabled in the fork root, I appear to be unable to do that:

```
batch response: @sxlijin can not upload new objects to public fork sxlijin/sqlfmt-docs
```

To do so you'll want to create a `.gitattributes` file with the following contents:

```
*.png filter=lfs diff=lfs merge=lfs -text
```

### CODE REVIEW

**Comment by tconbeer** [comment]
Thanks for the tip about git-lfs. That's done if you want to try pushing again.

**Comment by sxlijin** [comment]
Thanks; still getting errors though. I think you'll also need to add `static/img/logo.png` to LFS, [to tell GitHub to bootstrap LFS storage for this repo](https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-239831273). Maybe via some version of this?:

```
cp static/img/logo.png{,.bak}
git rm -f static/img/logo.png
mv static/img/logo.png{.bak,}
git add static/img/logo.png
```

**Comment by sxlijin** [comment]
Ping for you @tconbeer :)

**Comment by tconbeer** [comment]
Thanks again, @sxlijin -- I'm just going to merge this as-is and I'll figure the LFS stuff out later.

**Pull request merged**
